## {width=22%}

```{r}
#| context: server
suppressMessages(library(deSolve))

logist <- function (t, x, parms) {
  with(as.list(c(x, parms)),{
    dN <- r_max * N * (1-N/K)
    list(c(dN))
  })
}
parms  <- c(r_max=0.1, K=10)
times  <- seq(0, 100, by=0.5)
y0     <- c(N=1)

simulate_logist <- reactive({
  parms  <- c(r_max=input$logist_r,  K=input$logist_K)
  y0 <- c(N = input$logist_N0)
  res <- ode(y0, times, logist, parms, method = "adams")
})

#| context: server
output$logist <- renderPlotly({
  res <- simulate_logist()
  
  # 1. Übersetzungen als reine Text-Variablen holen
  label_time      <- i18n$t("Time")
  label_abundance <- i18n$t("Abundance")
  
  # 2. Daten mit festen, sicheren Spaltennamen verarbeiten (kein !!sym nötig!)
  df_plot <- res |>
    as.data.frame() |>
    pivot_longer(cols = c("N"), names_to = "Population", values_to = "value_abundance")
  
  # 3. Plot erstellen: Ästhetiken (aes) nutzen statische Namen
  gg <- ggplot(df_plot, aes(x = time, y = value_abundance, color = Population)) + 
    geom_line() + 
    scale_color_manual(values = c("#69af22")) +
    labs(x = label_time, y = label_abundance) + 
    theme(legend.position = "none") + 
    figure_theme

  # 4. Übergabe an Plotly
  ggplotly(gg)  
})
```

```{r}
inputPanel(
  h2(i18n$t("Initial Values")),
  numericInput(
    "logist_N0", label = i18n$t("N0: Abundance"), value = 1.0, min = 0, max = 1000, step = 0.1
  ),
  h2(i18n$t("Parameters")),
  sliderInput(
    "logist_r", label = i18n$t("r_max: Growth rate"), value = 0.1, min = 0, max = 1, step = 0.02
  ),
  sliderInput(
    "logist_K", label = i18n$t("K: Carrying capacity"), value = 100, min = 0, max = 1000, step = 10
  )
)
```

## {width=40%}
```{r}
plotlyOutput("logist")
```
