## {width=22%}


```{r}
#| context: server
suppressMessages(library(deSolve))

lv <- function (t, x, parms) {
  with(as.list(c(x, parms)),{
    dB <- a * B - b * R * B
    dR <- c * R * B - d * R
    list(c(dB, dR))
  })
}
parms  <- c(a = 0.1, b=0.1, c = 0.1, d = 0.1)
times  <- seq(0, 200, by = 0.2)
y0     <- c(B = 1, R = 0.5)

simulate <- reactive({
  parms  <- c(a = input$lv_a,  b = input$lv_b, c = input$lv_c, d = input$lv_d)
  y0     <- c(B = input$lv_B0, R = input$lv_R0)
  res    <- ode(y0, times, lv, parms, method = "adams")
})

output$lotkavolterra <- renderPlotly({
  res <- simulate()
  
  lv_df <- res |>
    as.data.frame() |>
    rename(Beute = B, Räuber = R) |>
    pivot_longer(cols = c("Beute", "Räuber"), 
                 names_to = "Population", values_to = "Abundanz") |>
    rename(Zeit = time)

  if (input$lv_grid == FALSE) {
    gg <- lv_df |>
      ggplot(aes(Zeit, Abundanz, color=Population)) + geom_line() + 
      scale_color_manual(values=c("#69af22", "#009de0"))
 
    
  } else {
    
    # Simple peak detection
    prey_peaks <- lv_df|>
      dplyr::filter(Population == "Beute") |>
      dplyr::slice(which(diff(sign(diff(Abundanz))) == -2))
    
    pred_peaks <- lv_df|>
      dplyr::filter(Population == "Räuber") |>
      dplyr::slice(which(diff(sign(diff(Abundanz))) == -2))
    
    
    #write.table(lv_df, file="lv_df.log")
    #write.table(prey_peaks, file="prey.log")

    gg <- lv_df |>
      ggplot(aes(Zeit, Abundanz, color=Population)) + geom_line() + 
      scale_color_manual(values = c("#69af22", "#009de0")) +
      scale_x_continuous(
        breaks = breaks_pretty(n = 10),      # ~10 major breaks, adapts to data
        minor_breaks = breaks_width(5)       # minor breaks every 5 units, adapts to data
      ) +
      scale_y_continuous(
        breaks = breaks_pretty(n = 10)       # ~10 major breaks for y, adapts to data
      )

    lwd <- 0.3 # line width for peaks and equilibria
    
    gg <- gg + geom_vline(aes(xintercept = Zeit), colour = "#009de0", linetype = "dotted", linewidth = lwd, data = pred_peaks)
    gg <- gg + geom_vline(aes(xintercept = Zeit), colour = "#69af22", linetype = "dotted", linewidth = lwd, data = prey_peaks)
    
    
    gg <- gg + geom_hline(aes(yintercept = input$lv_a/input$lv_b), colour = "#009de0", linewidth = lwd, linetype = "dotted")
    gg <- gg + geom_hline(aes(yintercept = input$lv_d/input$lv_c), colour = "#69af22", linewidth = lwd, linetype = "dotted")


    ## Additional simulations
    ## we simulate it twice, one time for the periods of prey, one time for predator,
    ## where periods are defined from maximum to maximum
    parms  <- c(a=input$lv_a,  b=input$lv_b, c=input$lv_c, d=input$lv_d)
    y0 <- c(B = input$lv_B0, R = input$lv_R0)
    
    ## simulation with peakstepsize for prey
    npeaks <- nrow(prey_peaks)
    times  <- c(0, seq(prey_peaks$Zeit[1], prey_peaks$Zeit[npeaks], length.out = 1 + 10 * (npeaks - 1)))

    res <- ode(y0, times, lv, parms, method = "adams", rtol = 1e-12)
    
    period1 <- res |>
      as.data.frame() |>
      pivot_longer(cols=c("B", "R"), 
                   names_to="Population", values_to="Abundanz") |>
      rename(Zeit = time) |>
      dplyr::filter(Population == "B") |>
      dplyr::filter(Zeit > 0) # remove initial value
    
    ## simulation with peakstepsize for predator
    npeaks <- nrow(pred_peaks)
    times  <- c(0, seq(pred_peaks$Zeit[1], pred_peaks$Zeit[npeaks], length.out = 1 + 10 * (npeaks - 1)))

    res <- ode(y0, times, lv, parms, method = "adams", rtol = 1e-12)
    
    period2 <- res |>
      as.data.frame() |>
      pivot_longer(cols=c("B", "R"), 
                   names_to="Population", values_to="Abundanz") |>
      rename(Zeit = time) |>
      dplyr::filter(Population == "R") |>
      dplyr::filter(Zeit > 0) # remove initial value
    
    period <- bind_rows(period1, period2)
    
    
    gg <- gg + 
      geom_point(aes(Zeit, Abundanz, color = Population), data = period, size = 0.8) +
     
      scale_color_manual(values=c("forestgreen", "#69af22", "navy", "#009de0")) #+
      #scale_color_manual(values=c("B"="forestgreen", "R"="blue"))
    
    query <- parseQueryString(session$clientData$url_search)

      if (!is.null(query$cheat) &&  "cheat" %in% names(query())) {
      gg <- gg +  geom_text(aes(Zeit, Abundanz, label = round(Abundanz, 2), color = Population), 
        data=period, position = position_nudge(x = 4), size = 3, fontface = "bold")
    }

  }
  
  gg <- gg +  theme(legend.position = "bottom")

  ggplotly(gg)
  
})

## --------- download functionality ----------------------

# Parse the query string to check for the "download" parameter
# query <- reactive({
#   parseQueryString(session$clientData$url_search)
# })

# Define the download handler
output$downloadData <- downloadHandler(
  filename = function() {
    paste("simulation-", format(Sys.time(), "%Y%m%d-%H%M%S"), ".csv", sep = "")
  },
  content = function(file) {
    # Get the simulation data
    res <- simulate()
    
    # Convert the simulation data to a data frame
    lv_df <- res |>
      as.data.frame() |>
      rename(Beute = B, Raeuber = R, Zeit = time)
    
    # Write the data to a CSV file, German format with comma and semicolon
    write.table(lv_df, file, row.names = FALSE, quote = FALSE, dec=",", sep=";")
  }
)

# Conditionally render the download button based on the query parameter
#output$downloadUI <- renderUI({
  #query <- query()
  #if (!is.null(query$download) &&  ("download" %in% names(query()))) {
  #  downloadButton("downloadData", "Download")
  #} else {
  #  NULL  # Do not show the download button
  #}
#})

```

```{r}
inputPanel(
  h3("Anfangswerte"),
  tags$div(title="Abundanz der Beute zum Zeitpunkt t=0",
           numericInput(
             "lv_B0", label = "B0: Beute", width="48%",
             value = 1.0, min = 0, max = 2, step = 0.1
           )),
  tags$div(title="Abundanz des Räubers zum Zeitpunkt t=0",
           numericInput(
             "lv_R0", label = "R0: Räuber", width="48%",
             value = 0.5, min = 0, max = 2, step = 0.1
           )),
  h3("Parameter"),
  tags$div(title="Vermehrungsrate des Phytoplanktons (Beutepopulation)",
           sliderInput(
             "lv_a", label = "a: Vermehrungsrate Beute", 
             value = 0.1, min = 0, max = 1, step = 0.02
           )),
  tags$div(title="Fraßverlust des Phytoplanktons (Beute) durch Fraß der Daphnien (Räuber)",
           sliderInput(
             "lv_b", label = "b: Verlust Beute durch Fraß", 
             value = 0.1, min = 0, max = 1, step = 0.02
           )),
  tags$div(title="Zuwachseffizienz der Daphnien (Räuber) durch Nahrungsaufnahme",
           sliderInput(
             "lv_c", label = "c: Effizienz Räuber", 
             value = 0.1, min = 0, max = 1, step = 0.02
           )),
  tags$div(title="Sterberate der Daphnien (Räuber)",
           sliderInput(
             "lv_d", label = "d: Sterberate Räuber", 
             value = 0.1, min = 0, max = 1, step = 0.02
           )),
  checkboxInput("lv_grid", "Werte abtasten", value = FALSE),
  #uiOutput("downloadUI") # conditional version
  downloadButton("downloadData", "Download")
)
```

## {width=40%}
```{r}
plotlyOutput("lotkavolterra")
```

