## {width=22%}

```{r, echo=FALSE}
#| context: server
suppressMessages(library(deSolve))

resource <- function (time, y, parms) {
  with(as.list(c(y, parms)), {
    f <- P/(kP + P)
    dA_dt <- r * f * A
    dP_dt <- - r * 1/Y * f * A
    list(c(dA_dt, dP_dt))
  })
}

y0 <- c(
  A = 10,  # algae,      mol/m3 carbon
  P   =  5   # phosphorus, mol/m3 P
) # in mg/L
parms <- c(r = 0.1, kP = 0.5, Y = 41) # Y = C:P - Redfield ratio
times  <- seq(0, 200, by=1)

simulate_resource <- reactive({
  parms  <- c(r=input$resource_r,  kP=input$resource_kP, Y=input$resource_Y)
  y0 <- c(A = input$resource_A, P=input$resource_P)
  res <- ode(y0, times, resource, parms, method = "adams")
})

output$resource <- renderPlotly({
  res <- simulate_resource()
  
  gg <- res |>
    as.data.frame() |>
    rename(Phytoplankton=A, Phosphor=P) |>
    pivot_longer(cols=c("Phosphor", "Phytoplankton"), 
                 names_to = "Zustandsgröße", values_to = "Abundanz") |>
    mutate(Population=factor(Zustandsgröße, levels=c("Phosphor", "Phytoplankton"))) |>
    rename(Zeit = time) |>
    ggplot(aes(Zeit, Abundanz, color = Zustandsgröße)) + 
      geom_line() + 
      facet_wrap(~ Zustandsgröße, scales="free", nrow=2, strip.position = "left", 
                 labeller = as_labeller(c(Phosphor = "Phosphor (P, mg/m3)", 
                                          Phytoplankton = "Phytoplankton (C, mg/m3)"))
                 
                 ) +
      ylab(NULL) +
      scale_color_manual(values=c("#f2aa8d", "#69af22")) +
      theme(legend.position="none", 
            #strip.background = element_blank(),
            strip.placement = "outside",
            plot.margin=margin(t = 0, r = 0, b = 10, l = 0, unit = "pt")) +
      xlab("Zeit (h)") +
      figure_theme

  ggplotly(gg)  
  
})
```

```{r}
#| fig-alt: "Input-Panel zur Einstellung von Anfangswerten und Modellparametern"
inputPanel(
  h2("Anfangswerte"),
  numericInput(
    "resource_A", label = "A0: Algen (C, mg/m3)", value = 1.0, min = 0, max = 2, step = 0.1
  ),
  numericInput(
    "resource_P", label = "P0: Phosphor (P, mg/m3)", value = 10, min = 0, max = 20, step = 0.1
  ),
  h2("Parameter"),
  sliderInput(
    "resource_r", label = "r: Wachstumsrate (1/h)", value = 0.1, min = 0, max = 1, step = 0.02
  ),
  sliderInput(
    "resource_kP", label = "Kp: Halbsättigung (P, mg/m3)", value = 5, min = 0.5, max = 20, step = .5
  ),
  sliderInput(
    "resource_Y", label = "Y: C/P-Verhältnis", value = 41, min = 0, max = 200, step = 5
  )
)
```

## {width=40%}
```{r}
#| fig-alt: "Zeitreihendiagramm mit dem zeitlichen Verlauf der Zustandsgrößen"
plotlyOutput("resource")
```
