## {width=22%}

```{r}
#| context: server
suppressMessages(library(deSolve))

growth <- function (t, x, parms) {
  with(as.list(c(x, parms)),{
    dN <- r * N
    list(c(dN))
  })
}

simulate_growth <- reactive({
  req(input$growth_continuous, input$t_max, input$growth_r, input$growth_N0)
  
  if (input$growth_continuous  == "continuous") {
    times  <- seq(0, input$t_max, length.out=101)
  } else {
    times  <- seq(0, input$t_max, by=1)
  }
  
  parms  <- c(r = input$growth_r)
  y0 <- c(N = input$growth_N0)
  
  ## continuous: analytical solution
  if (input$growth_continuous == "continuous") {
    res <- data.frame(
       time = times,
       N = y0 * exp(parms * times)
    )
  ## discrete: numerical integration
  } else {
    res <- as.data.frame(ode(y0, times, growth, parms, method = "euler"))
  }
})

#| context: server
output$growth <- renderPlotly({
  res <- simulate_growth()
  
  # Dynamically translate the plot axis labels
  label_time      <- i18n$t("Time")
  label_abundance <- i18n$t("Abundance")
  
  gg <- res |>
    as.data.frame() |>
    pivot_longer(cols=c("N"), names_to="Population", values_to=label_abundance) |>
    rename(!!sym(label_time) := time) |>
    ggplot(aes(!!sym(label_time), !!sym(label_abundance), color=Population)) + 
      scale_color_manual(values=c("#69af22")) +
      theme(legend.position="none") +
      figure_theme 
      
  if (input$growth_continuous == "continuous") {
    gg <- gg + geom_line()
  } else {
    gg <- gg + geom_point()
  }

  ggplotly(gg)
})
```

```{r}
# In Quarto Shiny dashboards, i18n$t needs to be called inside the UI rendering
# to dynamically respond to the respective setup context.
inputPanel(
  h2(i18n$t("Initial Values")),
  numericInput(
    "growth_N0", label = i18n$t("N0: Abundance"), value = 1, min = 0, max = 100, step = 1,
    width="50%"
  ),
  h2(i18n$t("Parameters")),
  sliderInput(
    "growth_r", label = i18n$t("r: Growth rate"), value = 1, min = -1.2, max = 1.2, step = 0.1
  ),
  h2(i18n$t("Control")),
  radioButtons(
    "growth_continuous", 
    label = i18n$t("Time steps"),
    choices = setNames(
      c("discrete", "continuous"), 
      c(i18n$t("discrete"), i18n$t("continuous"))
    ), 
    selected = "discrete"
  ),
  sliderInput(
    "t_max", label = i18n$t("Simulation time"), value = 10, min = 5, max = 200, step = 5
  )
)
```

## {width=40%}
```{r}
plotlyOutput("growth")
```
