## {width=22%}

```{r, echo=FALSE}
#| context: server
suppressMessages(library(deSolve))

resource <- function (time, y, parms) {
  with(as.list(c(y, parms)), {
    f <- P/(kP + P)
    dA_dt <- r * f * A
    dP_dt <- - r * 1/Y * f * A
    list(c(dA_dt, dP_dt))
  })
}

y0 <- c(
  A = 10,  # algae,      mol/m3 carbon
  P   =  5   # phosphorus, mol/m3 P
) # in mg/L
parms <- c(r = 0.1, kP = 0.5, Y = 41) # Y = C:P - Redfield ratio
times  <- seq(0, 200, by=1)

simulate_resource <- reactive({
  parms  <- c(r=input$resource_r,  kP=input$resource_kP, Y=input$resource_Y)
  y0 <- c(A = input$resource_A, P=input$resource_P)
  res <- ode(y0, times, resource, parms, method = "adams")
})

output$resource <- renderPlotly({
  res <- simulate_resource()
  
  # Fetch dynamic translations for labels and structural variables
  label_time          <- i18n$t("Time (h)")
  label_abundance     <- i18n$t("Abundance")
  label_phosphorus    <- i18n$t("Phosphorus")
  label_phytoplankton <- i18n$t("Phytoplankton")
  label_state_var     <- i18n$t("State Variable")
  
  # Construct dynamic labeller values for the wrap headers
  facet_labels <- c(
    Phosphorus = i18n$t("Phosphorus (P, mg/m3)"),
    Phytoplankton = i18n$t("Phytoplankton (C, mg/m3)")
  )
  names(facet_labels) <- c(label_phosphorus, label_phytoplankton)
  
  gg <- res |>
    as.data.frame() |>
    rename(!!sym(label_phytoplankton) := A, !!sym(label_phosphorus) := P) |>
    pivot_longer(cols = c(!!sym(label_phosphorus), !!sym(label_phytoplankton)), 
                 names_to = label_state_var, values_to = label_abundance) |>
    mutate(Population = factor(!!sym(label_state_var), levels = c(label_phosphorus, label_phytoplankton))) |>
    rename(!!sym(label_time) := time) |>
    ggplot(aes(!!sym(label_time), !!sym(label_abundance), color = !!sym(label_state_var))) + 
      geom_line() + 
      facet_wrap(vars(!!sym(label_state_var)), scales="free", nrow=2, strip.position = "left", 
                 labeller = as_labeller(facet_labels)) +
      ylab(NULL) +
      scale_color_manual(values=c("#f2aa8d", "#69af22")) +
      theme(legend.position="none", 
            strip.placement = "outside",
            plot.margin=margin(t = 0, r = 0, b = 10, l = 0, unit = "pt")) +
      xlab(label_time) +
      figure_theme

  ggplotly(gg)  
  
})
```

```{r}
#| fig-alt: "Input panel for adjusting initial values and model parameters"
inputPanel(
  h2(i18n$t("Initial Values")),
  numericInput(
    "resource_A", label = i18n$t("A0: Algae (C, mg/m3)"), value = 1.0, min = 0, max = 2, step = 0.1
  ),
  numericInput(
    "resource_P", label = i18n$t("P0: Phosphorus (P, mg/m3)"), value = 10, min = 0, max = 20, step = 0.1
  ),
  h2(i18n$t("Parameters")),
  sliderInput(
    "resource_r", label = i18n$t("r: Growth rate (1/h)"), value = 0.1, min = 0, max = 1, step = 0.02
  ),
  sliderInput(
    "resource_kP", label = i18n$t("Kp: Half-saturation (P, mg/m3)"), value = 5, min = 0.5, max = 20, step = .5
  ),
  sliderInput(
    "resource_Y", label = i18n$t("Y: C/P ratio"), value = 41, min = 0, max = 200, step = 5
  )
)
```

## {width=40%}
```{r}
#| fig-alt: "Time-series diagram showing the temporal progression of state variables"
plotlyOutput("resource")
```
